name: Automation Deployment

on:
  push:
    branches:
      - main  # Set the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Action to checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install Robocorp CLI
        run: |
          pip install -U rpaframework
          pip install -U robotframework-browser

      - name: Execute Automation Script
        run: |
          rcc run --agent auto --workspace "Mrfresh" --api-key ${{ secrets.ROBOCORP_API_KEY }}
   